name: PJJ
on:
  schedule:
    - cron: '0 */12 * * *'
  watch:
    types: [started]
  workflow_dispatch:
jobs:
  build:
   runs-on: ubuntu-latest
 steps:
      - name: Checkout
        run: |
          git clone https://github.com/wuhoushaonian/PJJ.git ~/PJJ
     - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7 
     - name: 'Install requirements'
        run: |
        cd ~/PJJ
        pip3.7 install -r requirements.txt
      - uses: nanasess/setup-chromedriver@master
      
        with:
