 name: 书

on:
  workflow_dispatch:
  schedule:
     - cron: '20 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        SQ_shuqiuserURL: ${{ secrets.SQ_shuqiuserURL }}		
        COOKIES_SPLIT: ${{ secrets.COOKIES_SPLIT }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/wuhoushaonian/yangquan.git ~/yangquan
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.SQ_shuqiuserURL
        run: |
          cd ~/yangquan
          git checkout main
          npm install
      - name: '运行 【书】'
        if: env.SQ_shuqiuserURL
        run: |
          cd ~/yangquan
          node Task/shuqi.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
